version: '3'
services:
  app:
    image: composer:2
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "composer install && php artisan key:generate && php artisan migrate && php-fpm"
    ports:
      - "8000:8000"
       - "8000:8000"
